### ISSUE TITLE
ipad masking issue

### ISSUE THREAD

**Issue by HappyIosDeveloper** [Marwan8/MAGlowingLabel#2]
Hi.
On the iPad, when we have a long label edge to edge of the screen, the half of the text is masked & not visible!

**Comment by HappyIosDeveloper** [comment]
To fix this issue, simply put the 'addGlowingEffect' function inside the 'MAGlowingLabel' class, into a DispatchQueue..

like this:

   ```
 required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        DispatchQueue.main.async {
            self.addGlowingEffect()
        }
    }
```

**Comment by Marwan8** [comment]
@UzumakiAlfredo Thanks for opening the issue and introduce the fix 

I have already updated the file with your fix ;)
